/**
 * Mock 数据 —— 当后端 API 不可用时自动降级使用
 * 你可以直接修改这里来定制门户展示内容
 */

export const MOCK_CATEGORIES = [
  { id: 1, name: '效率工具', icon: 'Tools', description: '提升工作效率的实用工具', sortOrder: 1 },
  { id: 2, name: '数据分析', icon: 'DataAnalysis', description: '数据可视化与分析平台', sortOrder: 2 },
  { id: 3, name: 'API服务', icon: 'Connection', description: '接口管理与测试服务', sortOrder: 3 },
  { id: 4, name: '娱乐应用', icon: 'Sugar', description: '有趣的日常应用', sortOrder: 4 },
]

export const MOCK_PROJECTS = [
  {
    id: 1,
    name: '任务管理系统',
    description: '一个简洁高效的任务管理工具，支持团队协作、任务分配和进度追踪，大幅提升团队工作效率。',
    url: 'https://github.com',
    icon: '',
    categoryId: 1,
    categoryName: '效率工具',
    techStack: 'Spring Boot,Vue 3,MySQL',
    status: 'ACTIVE',
    isFeatured: true,
    sortOrder: 1,
    visitCount: 1280,
    githubUrl: 'https://github.com',
    tags: '效率,协作,任务',
    createTime: '2024-01-15T00:00:00',
    updateTime: '2024-06-01T00:00:00',
  },
  {
    id: 2,
    name: '数据可视化平台',
    description: '基于 ECharts 的数据可视化平台，支持多种图表类型，数据实时更新，帮助业务快速决策。',
    url: 'https://github.com',
    icon: '',
    categoryId: 2,
    categoryName: '数据分析',
    techStack: 'Vue 3,ECharts,Spring Boot',
    status: 'ACTIVE',
    isFeatured: true,
    sortOrder: 2,
    visitCount: 956,
    githubUrl: '',
    tags: '图表,可视化,数据',
    createTime: '2024-02-20T00:00:00',
    updateTime: '2024-06-10T00:00:00',
  },
  {
    id: 3,
    name: '接口管理平台',
    description: '类似 Postman 的在线接口测试工具，支持团队共享接口文档，自动生成 Mock 数据，提高联调效率。',
    url: 'https://github.com',
    icon: '',
    categoryId: 3,
    categoryName: 'API服务',
    techStack: 'Spring Boot,Redis,Vue 3',
    status: 'ACTIVE',
    isFeatured: false,
    sortOrder: 3,
    visitCount: 743,
    githubUrl: 'https://github.com',
    tags: 'API,接口,Mock',
    createTime: '2024-03-10T00:00:00',
    updateTime: '2024-05-20T00:00:00',
  },
  {
    id: 4,
    name: '在线音乐播放器',
    description: '简洁优雅的在线音乐播放器，支持歌词滚动显示、播放列表管理和本地音乐导入。',
    url: 'https://github.com',
    icon: '',
    categoryId: 4,
    categoryName: '娱乐应用',
    techStack: 'Vue 3,Web Audio API',
    status: 'ACTIVE',
    isFeatured: false,
    sortOrder: 4,
    visitCount: 612,
    githubUrl: '',
    tags: '音乐,播放器',
    createTime: '2024-04-05T00:00:00',
    updateTime: '2024-06-15T00:00:00',
  },
  {
    id: 5,
    name: '个人记账本',
    description: '简单易用的个人财务记账工具，支持收支统计、预算设置和多维度图表分析。',
    url: 'https://github.com',
    icon: '',
    categoryId: 1,
    categoryName: '效率工具',
    techStack: 'Spring Boot,Vue 3,H2',
    status: 'ACTIVE',
    isFeatured: true,
    sortOrder: 5,
    visitCount: 489,
    githubUrl: 'https://github.com',
    tags: '记账,财务,统计',
    createTime: '2024-04-18T00:00:00',
    updateTime: '2024-06-20T00:00:00',
  },
  {
    id: 6,
    name: '简历生成器',
    description: '在线简历制作工具，提供多种精美模板，支持实时预览与 PDF 一键导出。',
    url: 'https://github.com',
    icon: '',
    categoryId: 1,
    categoryName: '效率工具',
    techStack: 'Vue 3,PDF.js,Spring Boot',
    status: 'MAINTENANCE',
    isFeatured: false,
    sortOrder: 6,
    visitCount: 328,
    githubUrl: '',
    tags: '简历,PDF,模板',
    createTime: '2024-05-01T00:00:00',
    updateTime: '2024-06-25T00:00:00',
  },
]

export const MOCK_STATS = {
  totalProjects: MOCK_PROJECTS.length,
  activeProjects: MOCK_PROJECTS.filter(p => p.status === 'ACTIVE').length,
  totalVisits: MOCK_PROJECTS.reduce((sum, p) => sum + p.visitCount, 0),
  totalCategories: MOCK_CATEGORIES.length,
}

/**
 * 个人信息配置 —— 修改这里来自定义你的门户
 */
export const PROFILE = {
  name: '全栈开发者',
  title: '独立开发者 / Full-Stack Engineer',
  avatar: '',   // 可填头像URL
  bio: '热爱编程，专注于构建解决真实问题的产品。擅长 Java 后端与 Vue 前端开发，喜欢将想法快速变成可用的应用。',
  github: 'https://github.com',
  email: '',
  blog: '',
  skills: [
    { name: 'Java / Spring Boot', level: 90 },
    { name: 'Vue 3 / TypeScript', level: 85 },
    { name: 'MySQL / Redis', level: 80 },
    { name: 'Docker / Nginx', level: 70 },
    { name: 'React / Node.js', level: 60 },
  ],
  skillTags: [
    'Java', 'Spring Boot', 'Vue 3', 'MySQL', 'Redis',
    'Docker', 'Nginx', 'Git', 'Linux', 'TypeScript',
    'MyBatis', 'ElementPlus', 'RESTful API',
  ],
}
